version: '3.6'

services:
  rabbit:
    image: "rabbitmq:3.9-management"
    environment: 
      RABBITMQ_ERLANG_COOKIE: "SWQOK)DSQALRPCLINMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports: 
      - "15672:15672"
      - "5672:5672"